name: 'OCaml tests'

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  run:
    name: Build
    runs-on: '${{ matrix.os }}'
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2
      - id: ocaml-resp-opam-cache
        name: 'OCaml/Opam cache'
        uses: actions/cache@v2
        with:
          key: 'ocaml-resp-opam-${{ matrix.ocaml-version }}-${{ matrix.os }}'
          path: ~/.opam
      - name: 'Use OCaml ${{ matrix.ocaml-version }}'
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: '${{ matrix.ocaml-version }}'
      - name: 'Set Opam env'
        run: 'opam env >> $GITHUB_ENV'
      - name: 'Add Opam switch to PATH'
        run: 'opam var bin >> $GITHUB_PATH'
      - run: 'OPAMSOLVERTIMEOUT=3600 opam install . --deps-only --with-test'
      - name: 'Run OCaml tests'
        run: 'opam exec -- dune runtest'
    strategy:
      fail-fast: true
      matrix:
        ocaml-version:
          - 4.11.1
          - 4.10.0
          - 4.09.1
          - 4.08.1
        os:
          - macos-latest
          - ubuntu-latest
